"""Shared model definitions used across agents and orchestrator."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


def utc_now() -> str:
    """Return an ISO-8601 timestamp in UTC."""
    return datetime.now(timezone.utc).isoformat()


class MessageType(str, Enum):
    """Supported inter-agent message types."""

    TASK = "TASK"
    REVIEW = "REVIEW"
    FEEDBACK = "FEEDBACK"
    APPROVAL = "APPROVAL"
    STATUS = "STATUS"


class ReviewStatus(str, Enum):
    """Review outcomes for peer-review topologies."""

    APPROVED = "APPROVED"
    REVISION_NEEDED = "REVISION_NEEDED"


@dataclass
class Artifact:
    """Versioned artifact generated by an agent."""

    artifact_id: str
    artifact_type: str
    producer: str
    content: Any
    version: int = 1
    created_at: str = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "artifact_id": self.artifact_id,
            "artifact_type": self.artifact_type,
            "producer": self.producer,
            "content": self.content,
            "version": self.version,
            "created_at": self.created_at,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Artifact":
        return cls(
            artifact_id=data["artifact_id"],
            artifact_type=data["artifact_type"],
            producer=data["producer"],
            content=data.get("content"),
            version=data.get("version", 1),
            created_at=data.get("created_at", utc_now()),
            metadata=data.get("metadata", {}),
        )


@dataclass
class AgentMessage:
    """Message exchanged between agents or orchestrator."""

    sender: str
    receiver: str
    content: str
    msg_type: MessageType = MessageType.TASK
    artifacts: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "sender": self.sender,
            "receiver": self.receiver,
            "content": self.content,
            "msg_type": self.msg_type.value,
            "artifacts": self.artifacts,
            "timestamp": self.timestamp,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AgentMessage":
        msg_type_value = data.get("msg_type", MessageType.TASK.value)
        return cls(
            sender=data["sender"],
            receiver=data["receiver"],
            content=data.get("content", ""),
            msg_type=MessageType(msg_type_value),
            artifacts=list(data.get("artifacts", [])),
            timestamp=data.get("timestamp", utc_now()),
            metadata=dict(data.get("metadata", {})),
        )


@dataclass
class ReviewResult:
    """Structured review result returned by agent review steps."""

    status: ReviewStatus
    comments: list[str] = field(default_factory=list)
    blocking_issues: list[str] = field(default_factory=list)
    reviewer: str = ""
    timestamp: str = field(default_factory=utc_now)

    def to_dict(self) -> dict[str, Any]:
        return {
            "status": self.status.value,
            "comments": self.comments,
            "blocking_issues": self.blocking_issues,
            "reviewer": self.reviewer,
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ReviewResult":
        return cls(
            status=ReviewStatus(data["status"]),
            comments=list(data.get("comments", [])),
            blocking_issues=list(data.get("blocking_issues", [])),
            reviewer=data.get("reviewer", ""),
            timestamp=data.get("timestamp", utc_now()),
        )
